nama = input ("nama kamu siapa?")
umur = input ("berapa umurmu?")
sekolah = input ("sekolah di mana kamu?")
hobi = input ("hobimu apa?")
kelas = input ("kamu kelas berapa?")
sodara = input ("kamu berapa bersaudara?")
rumah = input ("rumah kamu dimana?")
makanan = input ("apa makanan kesukaan kamu?")
minuman = input ("apa minuman kesukaan kamu?")
pacar = input ("kamu udh punya pacar?")
print ("Hallo, nama saya",nama,"umur saya",umur,"sekolah di mana kamu",sekolah,"hobimu apa",hobi,"kelas berapa kamu",kelas,"berapa bersodara kmu",sodara,"rumah kamu dimana",rumah,"apa makanan kesukaan kamu",makanan,"apa makanan kesukaan kamu",minuman,"kamu udah punya pacar",pacar,)